apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy-pod
        args:
          - --provider=keycloak-oidc
          - --client-id=oauth2-proxy
          - --client-secret=o8NBJQ16Sh5zGSmk4LSEO9HouR0kYlrb
          - --redirect-url=https://test.snappypreview.com/oauth2/callback
          - --oidc-issuer-url=https://auth.snappypreview.com/realms/master
          - --email-domain=*                
          - --cookie-secret=gMGJGeNSVvaexhtRX_3V811lfm7Ekhr5F02DD7LYyxc=
          #- --errors-to-info-log=true
        image: quay.io/oauth2-proxy/oauth2-proxy:latest        
        ports:
        - containerPort: 4180
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy-service
spec:
  selector:
    app: oauth2-proxy
  ports:
  - name: http
    port: 4180
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy-ingress
  annotations:            
    cert-manager.io/issuer: letsencrypt-nginx
spec:
  ingressClassName: nginx
  rules:
  - host: test.snappypreview.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: oauth2-proxy-service
              port: 
                number: 4180        
  tls:
  - hosts:
    - test.snappypreview.com    
    secretName: cert-oauth